export const NFT_ABI = [
  { name: "mint", type: "function", stateMutability: "payable",
    inputs: [{ name: "quantity", type: "uint256" }], outputs: [] },
  { name: "totalSupply", type: "function", stateMutability: "view",
    inputs: [], outputs: [{ type: "uint256" }] },
  { name: "mintActive", type: "function", stateMutability: "view",
    inputs: [], outputs: [{ type: "bool" }] },
  { name: "mintedPerWallet", type: "function", stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }], outputs: [{ type: "uint256" }] },
  { name: "tokensOfOwner", type: "function", stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }], outputs: [{ type: "uint256[]" }] },
  { name: "tokenURI", type: "function", stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }], outputs: [{ type: "string" }] },
  { name: "remainingSupply", type: "function", stateMutability: "view",
    inputs: [], outputs: [{ type: "uint256" }] },
  { name: "MINT_PRICE", type: "function", stateMutability: "view",
    inputs: [], outputs: [{ type: "uint256" }] },
  { name: "MAX_SUPPLY", type: "function", stateMutability: "view",
    inputs: [], outputs: [{ type: "uint256" }] },
] as const;

export const MARKETPLACE_ABI = [
  { name: "list", type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "tokenId", type: "uint256" }, { name: "price", type: "uint256" }], outputs: [] },
  { name: "delist", type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "tokenId", type: "uint256" }], outputs: [] },
  { name: "updatePrice", type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "tokenId", type: "uint256" }, { name: "newPrice", type: "uint256" }], outputs: [] },
  { name: "buy", type: "function", stateMutability: "payable",
    inputs: [{ name: "tokenId", type: "uint256" }], outputs: [] },
  { name: "makeOffer", type: "function", stateMutability: "payable",
    inputs: [{ name: "tokenId", type: "uint256" }, { name: "duration", type: "uint256" }], outputs: [] },
  { name: "acceptOffer", type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "tokenId", type: "uint256" }, { name: "offerIndex", type: "uint256" }], outputs: [] },
  { name: "cancelOffer", type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "tokenId", type: "uint256" }, { name: "offerIndex", type: "uint256" }], outputs: [] },
  { name: "getActiveListings", type: "function", stateMutability: "view",
    inputs: [], outputs: [{ type: "uint256[]" }] },
  { name: "getActiveListingsPage", type: "function", stateMutability: "view",
    inputs: [{ name: "offset", type: "uint256" }, { name: "limit", type: "uint256" }],
    outputs: [{ name: "tokenIds", type: "uint256[]" }, { name: "listingData", type: "tuple[]",
      components: [{ name: "seller", type: "address" }, { name: "price", type: "uint256" }, { name: "active", type: "bool" }] }] },
  { name: "listings", type: "function", stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "seller", type: "address" }, { name: "price", type: "uint256" }, { name: "active", type: "bool" }] },
  { name: "getOffers", type: "function", stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ type: "tuple[]", components: [{ name: "buyer", type: "address" }, { name: "price", type: "uint256" }, { name: "expiry", type: "uint256" }, { name: "active", type: "bool" }] }] },
  { name: "feePercent", type: "function", stateMutability: "view",
    inputs: [], outputs: [{ type: "uint256" }] },
] as const;

export const RARITY_ABI = [
  { name: "scoreOf", type: "function", stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }], outputs: [{ type: "uint256" }] },
  { name: "rankOf", type: "function", stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }], outputs: [{ type: "uint256" }] },
  { name: "tierOf", type: "function", stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }], outputs: [{ type: "string" }] },
  { name: "rarityOf", type: "function", stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "score", type: "uint256" }, { name: "rank", type: "uint256" }, { name: "tier", type: "string" }] },
  { name: "rarityBatch", type: "function", stateMutability: "view",
    inputs: [{ name: "tokenIds", type: "uint256[]" }],
    outputs: [{ name: "scores", type: "uint256[]" }, { name: "ranks", type: "uint256[]" }, { name: "tiers", type: "string[]" }] },
  { name: "locked", type: "function", stateMutability: "view",
    inputs: [], outputs: [{ type: "bool" }] },
] as const;
